---
title: "Extend reference"
output: html_notebook
---

# Setup
```{r}
library(Biostrings)
library(here)
library(tidyverse)
```

# Read in data
```{r}
# Read in current version of reference
current <- 
     here('data', 
          'processed', 
          'dada2-compatible', 
          'trnL', 
          'trnLGH.fasta') %>% 
     readDNAStringSet()
```

# Cleaning up current reference
```{r}
# Combine species name and sequence to make unique identifier
# First, remove numbers
head(names(current))
names(current) <- gsub('^\\d+\\s', 
                       '',
                       names(current))

head(names(current))
```

```{r}
# Make joint string for each sequence
joint <- paste(names(current), 
               current, 
               sep = '_')

head(joint)
```

```{r}
any(duplicated(joint))
```

```{r}
sum(duplicated(joint))
length(joint)
```

```{r}
# Make unique
joint <- unique(joint)
length(joint)
```

```{r}
any(duplicated(joint))
```

```{r}
# Check for degenerate nucleotide characters
degenerate <- grep('_[AGCT]+[^AGCT]+', joint)

joint[degenerate]

# Remove these:
joint <- joint[!grepl('_[AGCT]+[^AGCT]+', joint)]
```

```{r}
# Re-index
joint <- 
     joint %>% 
     sort() %>% 
     paste(
          seq_along(.),
          .
     )
```

```{r}
# Separate sequence and name
split <- str_split(joint, 
                   pattern = '_')

new <- lapply(split, '[[', 2)
names(new) <- lapply(split, '[[', 1)
```


```{r}
# Save
new <- DNAStringSet(unlist(new))
new
```

```{r}
# Write to file
# writeXStringSet(new,
#                 here('data', 'processed', 'dada2-compatible', 'trnL',
#                      'trnLGH.fasta'))
```

# Add new sequences

```{r}
# Read in sequences to be added
additional <- 
     here('data', 'processed', 'sql-compatible', 
          '20210426_kenya-abc additions.csv') %>%
          # '20210607_chomp-onr additions.csv') %>% 
          # '20210617_pomms additions.csv') %>% 
          # '20210814_pomms additions.csv') %>% 
     read_csv()

# Format as a DNAStringSet
addseqs <- additional$sequence
names(addseqs) <- additional$species_name
```

Check if any are already present by a combination of their name and sequence. Needs to be this combo, because we want to duplicate a sequence if we also 
```{r}
# Set of current sequences
head(names(current))
names(current) <- gsub('^\\d+\\s', 
                       '',
                       names(current))

head(names(current))
```

```{r}
# Make joint string for each sequence
joint.current <- paste(names(current), 
               current, 
               sep = '_')

head(joint.current)
```

```{r}
# Proposed additions
joint.add <- paste(names(addseqs), 
               addseqs, 
               sep = '_')

head(joint.add)
```

```{r}
length(addseqs)
# If any sequences are duplicated
if (any(joint.add %in% joint.current)){
     # Show what's duplicated
     print(addseqs[which(joint.add %in% joint.current)])
     # Remove it
     addseqs <- addseqs[!(joint.add %in% joint.current)]
}
# Check difference in length
length(addseqs)
```

```{r}
# Combine
new <- c(current, addseqs)
```

```{r}
# Sort and add integer index
new <- new[sort(names(new))]
names(new) <- 
     paste(seq_along(new),
           names(new))
new
```

```{r}
# Write to file
writeXStringSet(new,
                here('data', 'processed', 'dada2-compatible', 'trnL',
                     'trnLGH.fasta'))
```

After this, update in Git.