get_binomial <- function(reference, entry=7){
     # Returns species-level entries in a DNAStringSet to be written
     # to FASTA for use as a reference database.
     
     # 'reference' is a dada2-formatted header as would be used in the 
     # reference database passed to dada2's assignTaxonomy() function.
     # 'entry' is the level of the header that has the name entry of interest:
     # if generated by make_reference.R, the terminal entry is the 
     # accession number and the second-to-last (the seventh entry) is the
     # traditional binomial name.
     split <- strsplit(names(reference), ';')
     species <- lapply(split, '[[', entry) %>% unlist() 
     species
}